nodeLinker: hoisted
enablePrePostScripts: true

patchedDependencies:
  expo-sqlite@57.0.2: patches/expo-sqlite@57.0.2.patch
  react-native-ios-utilities@5.2.0: patches/react-native-ios-utilities@5.2.0.patch

allowBuilds:
  browser-tabs-lock: false
  bufferutil: true
  core-js: false
  esbuild: true
  unrs-resolver: true
  utf-8-validate: true
